---
layout: default
comments: true
# other options
---

# Analytics
analytics:
  provider               : "google-gtag" 
                          # false (default), "google", "google-universal", "google-gtag", "custom"
  google:
    tracking_id          : "G-222FYY6RNR"
    anonymize_ip         : # true, false (default)
